Repository BulletBoxProject/BulletBox-project-FE-, pull requests merged in 2023-02, with the labels that each got.

#105 #75 feat: 날짜 선택 후 할 일 추가 기능
  src/components/common/calendar/MainCalendar.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/components/CalendarModal.jsx
  src/components/dailyLog/components/ModalFavoriteTodo.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/shared/Router.jsx
Labels: feat

#109 feat: 일기장 페이지조회, 작성 및 수정
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/components/EmotionButton.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateBtn.jsx
  src/components/search/components/SearchTodo.jsx
  src/components/search/components/SearchTodoBullet.jsx
  src/components/search/screen/SearchContainer.jsx
  src/components/signup/components/SignUpInput.jsx
  src/img/emotion/angry-1.svg
  src/img/emotion/angry.svg
  src/img/emotion/excited-1.svg
  src/img/emotion/excited.svg
  src/img/emotion/happy-1.svg
  src/img/emotion/happy.svg
  src/img/emotion/sad-1.svg
  src/img/emotion/sad.svg
  src/img/emotion/soso-1.svg
  src/img/emotion/soso.svg
  src/redux/config/configstore.jsx
  src/redux/modules/emotiondiarySlice.js
  src/shared/GlobalStyle.jsx
Labels: feat

#110 feat: 일기장 카멜케이스
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/logIn/components/LogInInput.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/emotiondiarySlice.js
Labels: feat

#112 design: 메인 페이지 할 일 목록 스타일링 작업 및 할 일 목록 조회 기능
  public/index.html
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/components/BulletSwitchList.jsx
  src/components/main/components/MainTodoCard.jsx
  src/components/main/screen/MainContainer.jsx
  src/img/bullet/circle-double.svg
  src/img/bullet/round-star-outline.svg
  src/img/bullet/triangle.svg
  src/layout/Layout.jsx
Labels: feat, design

#117 design: 전체적인 css수정
  public/index.html
  src/components/common/modal/AlertModal.jsx
  src/components/common/modal/ConfirmModal.jsx
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/logIn/components/SocialLogin.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddBtn.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/mypage/components/alwaystodo/screen/AlwaysTodoList.jsx
  src/components/mypage/components/category/components/CategoryAddBtn.jsx
  src/components/mypage/components/category/components/CategoryAddModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/mypage/components/category/screen/CategoryList.jsx
  src/components/search/components/SearchTodoBullet.jsx
  src/img/myPage/memo-5.svg
  src/redux/modules/favoriteSlice.js
  src/shared/GlobalStyle.jsx
Labels: design

#116 feat: 데일리로그, 메인페이지 미구현 기능들 추가 작업 및 메모 수정 기능 작업
  src/components/common/calendar/DailyLogCalendar.jsx
  src/components/common/calendar/MainCalendar.jsx
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/components/BulletSwitchList.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/components/CalendarModal.jsx
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/edit/components/EditMemoDiv.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/redux/modules/dailysSlice.js
Labels: feat, design

#119 feat: 데일리로그 피드백 반영 수정 작업
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/components/Option.jsx
  src/components/dailyLog/edit/components/CategorySelectDiv.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/shared/GlobalStyle.jsx
Labels: feat, design

#120 feat: 체험하기 버튼 기능구현, 전체적인 CSS 수정
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/components/EmotionButton.jsx
  src/components/logIn/components/KakaoLogin.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/logIn/components/SocialLogin.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/signup/components/SignUpInput.jsx
  src/core/kakaoLogin.jsx
  src/img/login/google.svg
  src/img/login/kakao.svg
  src/pages/KakaoLoginPage.jsx
  src/redux/modules/emotiondiarySlice.js
  src/redux/modules/favoriteSlice.js
  src/shared/Router.jsx
Labels: feat, design

#122 feat: 데일리로그 피드백 반영 수정 작업 #118
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/add/components/TimeSettingDiv.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/edit/components/EditMemoDiv.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/main/components/MainTodoCard.jsx
Labels: feat, design

#123 design: 피드백 design 수정작업
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/mypage/components/category/components/CategoryAddModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/search/components/SearchTodo.jsx
Labels: design

#129 design: 전체적인 css 수정, 데일리 예외처리
  public/favicon.ico
  public/favicon.svg
  public/index.html
  src/components/common/calendar/MainCalendar.jsx
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/edit/components/CategorySelectDiv.jsx
  src/components/dailyLog/edit/components/EditMemoDiv.jsx
  src/components/dailyLog/edit/components/EditTodoForm.jsx
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/components/EmotionButton.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/search/components/SearchTodo.jsx
  src/components/search/components/SearchTodoBullet.jsx
  src/components/signup/components/SignUpInput.jsx
  src/layout/footer/components/NavigationMenu.jsx
  src/redux/modules/emotiondiarySlice.js
  src/redux/modules/favoriteSlice.js
Labels: feat, design

#131 fix: routine 수정 렌더링 완료
  public/bulletbox.svg
  public/index.html
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/logIn/components/KakaoLogin.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/logIn/components/SocialLogin.jsx
  src/components/main/screen/MainContainer.jsx
  src/components/search/screen/SearchContainer.jsx
  src/pages/GoogleLoginPage.jsx
  src/pages/KakaoLoginPage.jsx
  src/redux/modules/favoriteSlice.js
  src/redux/modules/mainSlice.js
Labels: feat, design

#134 feat: 조회 페이지 목록 없을 경우 안내문구 추가 및 추가 페이지 이동 버튼 제공
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/components/ModalFavoriteTodo.jsx
  src/components/main/screen/MainContainer.jsx
Labels: feat, design

#136 feat: 시간 수정 기능 오류 수정
  src/components/common/calendar/MainCalendar.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/edit/components/SelectHoursList.jsx
  src/components/dailyLog/edit/components/SelectMinutesList.jsx
  src/components/dailyLog/edit/components/TimeSettingDiv.jsx
  src/redux/modules/dailysSlice.js
Labels: fix

#137 design: 기본 얼럿창 커스텀 얼럿 모달창으로 구현
  src/components/common/modal/AlertModal.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/main/screen/MainContainer.jsx
Labels: design

#138 feat: 탭바 선택 메뉴 표시 기능
  src/layout/footer/components/NavigationMenu.jsx
  src/redux/modules/dailysSlice.js
Labels: feat

#139 fix: 피드백 반영
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/mypage/components/category/components/CategoryAddModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/search/screen/SearchContainer.jsx
  src/layout/footer/components/NavigationMenu.jsx
  src/layout/header/components/HelpModal.jsx
  src/layout/header/components/SimpleSlider.jsx
  src/redux/modules/emotiondiarySlice.js
Labels: fix, feat, design

#140 #132 feat: 할 일 추가 후 모달 구현
  src/components/dailyLog/add/components/AddTodoInput.jsx
Labels: feat

#142 #132 fix: 할 일 추가 페이지 카테고리 불러오기 오류 수정
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/redux/modules/dailysSlice.js
Labels: fix

#141 fix: 피드백 수정사항 반영
  src/components/diary/components/DiaryContents.jsx
  src/components/logIn/components/SocialLogin.jsx
  src/components/logIn/screen/LogInContainer.jsx
  src/components/mypage/screen/MypageInfoButton.jsx
  src/components/search/screen/SearchContainer.jsx
  src/components/signup/screen/SignUpContainer.jsx
  src/layout/header/components/SimpleSlider.jsx
Labels: fix, design

#143 feat: 피드백 관련 수정 작업
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/add/components/SelectHoursList.jsx
  src/components/dailyLog/add/components/SelectMinutesList.jsx
  src/components/dailyLog/components/CalendarModal.jsx
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/components/SelectCategoryTodoShow.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/shared/Router.jsx
Labels: feat, design

#145 desgin: guideImg 크기 조절
  package.json
  src/components/common/modal/Modal.jsx
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/EmotionButton.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/img/Guide/guide1.svg
  src/img/Guide/guide2.svg
  src/img/Guide/guide3.svg
  src/img/Guide/guide4.svg
  src/img/Guide/guide5.svg
  src/img/Guide/guide6.svg
  src/img/Guide/guide7.svg
  src/layout/header/components/HelpModal.jsx
  src/layout/header/components/SimpleSlider.jsx
  src/layout/header/screen/Header.jsx
  src/redux/modules/favoriteSlice.js
  yarn.lock
Labels: feat

#148 feat: 캘린더 외부 클릭 시 닫힘 기능
  public/index.html
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
Labels: feat

#149 #design: routine 삭제창 confirm Modal로 변경
  src/components/common/SelectCategory.jsx
  src/components/common/modal/ConfirmModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/redux/modules/categorySlice.js
Labels: design

#150 feat: 데일리로그 페이지 에러 예외 처리 기능 #147
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/redux/modules/dailysSlice.js
Labels: feat

#152 refactor: guideImg 파일 교체, diaryPage Btn 접근가능한 이름추가
  public/index.html
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/components/EmotionButton.jsx
  src/img/Guide/guide1.svg
  src/img/Guide/guide2.svg
  src/img/Guide/guide3.svg
  src/img/Guide/guide4.svg
  src/img/Guide/guide5.svg
  src/img/Guide/guide6.svg
  src/img/Guide/guide7.svg
  src/layout/header/screen/Header.jsx
Labels: refactor

#153 서버 재배포
  public/index.html
  src/components/common/SelectCategory.jsx
  src/components/common/modal/ConfirmModal.jsx
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/components/EmotionButton.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/img/Guide/guide1.svg
  src/img/Guide/guide2.svg
  src/img/Guide/guide3.svg
  src/img/Guide/guide4.svg
  src/img/Guide/guide5.svg
  src/img/Guide/guide6.svg
  src/img/Guide/guide7.svg
  src/layout/header/screen/Header.jsx
  src/redux/modules/categorySlice.js
  src/redux/modules/dailysSlice.js
Labels: chore

#154 fix: date 한자리 일때 앞에 0 붙여주기
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/screen/DiaryContainer.jsx
Labels: fix

#155 #147 feat: 오류 메세지 화면 표시 기능
  src/components/dailyLog/screen/DailyLogContainer.jsx
Labels: feat

#156 feat: 오류 메세지 화면 표시 기능
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/diary/components/DiaryCalendar.jsx
  src/components/diary/components/DiaryContents.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/redux/config/configstore.jsx
Labels: fix, feat

#157 feat: 메인 페이지 에러 메시지 표시
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/layout/header/components/SimpleSlider.jsx
  src/redux/modules/dailysSlice.js
  src/redux/modules/mainSlice.js
  src/shared/Router.jsx
Labels: feat
