Repository BulletBoxProject/BulletBox-project-FE-, pull requests merged in 2023-01, with the labels that each got.

#2 개발환경세팅
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: chore

#3 Feature/#1
  package.json
  src/components/logIn/components/logInInput.jsx
  src/components/logIn/screen/logInContainer.jsx
  src/pages/Calendar.jsx
  src/pages/Login.jsx
  src/shared/GlobalStyle.jsx
  yarn.lock
Labels: chore

#9 Header,Footer 생성 완료 Feat/#8
  .gitignore
  package.json
  src/components/logIn/screen/LogInContainer.jsx
  src/components/signup/screen/SignUpContainer.jsx
  src/core/api.jsx
  src/core/cookieControler.jsx
  src/img/Menu_Icon.svg
  src/img/Question_Icon.svg
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/layout/footer/Footer.jsx
  src/layout/footer/components/Modal.jsx
  src/layout/header/components/DropdownMenu.jsx
  src/layout/header/components/useDetectClose.jsx
  src/layout/header/screen/Header.jsx
  src/shared/GlobalStyle.jsx
  yarn.lock
Labels: feat

#11 Feat/#10 feat: 버튼 컴포넌트 생 성, 헤더 위치 수정
  src/components/common/Button.jsx
  src/components/dailyLog/components/DailyLogNavi.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/layout/header/screen/Header.jsx
  src/pages/DailyLog.jsx
  src/pages/MonthlyLog.jsx
  src/shared/Router.jsx
Labels: feat

#12 feat: 토글버튼 생성, 카테고리 드롭다운 생성
  src/components/common/Button.jsx
  src/components/dailyLog/components/DailyLogNavi.jsx
  src/components/dailyLog/components/SelectGroup.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
Labels: feat

#14 캘린더 1차 css , 뒤로가기버튼 , modal창 바깥 클릭시 close - Feat/#9
  package.json
  src/components/calendar/Calendar.jsx
  src/components/logIn/screen/LogInContainer.jsx
  src/hooks/useOutSideClick.jsx
  src/layout/footer/Footer.jsx
  src/layout/footer/components/Modal.jsx
  src/layout/header/screen/Header.jsx
  yarn.lock
Labels: feat

#15 feat: 메인페이지 레이아웃 작업
  src/components/common/NavigationMenu.jsx
  src/components/common/SelectCategory.jsx
  src/components/dailyLog/components/SelectGroup.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/main/screen/MainContainer.jsx
Labels: feat

#21 img 파일 업로드, 헤더 레이아웃 - Feat/#9
  src/components/logIn/components/LogInInput.jsx
  src/components/logIn/screen/LogInContainer.jsx
  src/components/monthlyLog/screen/MonthlyLogContainer.jsx
  src/components/signup/screen/SignUpContainer.jsx
  src/img/bullet/asterisk-6.svg
  src/img/bullet/check-2.svg
  src/img/bullet/ex-4.svg
  src/img/bullet/meno-5.svg
  src/img/bullet/postpone-3.svg
  src/img/bullet/star-7.svg
  src/img/bullet/todo-1.svg
  src/img/log/dailylog.svg
  src/img/log/home.svg
  src/img/log/monthlylog.svg
  src/img/logo/logo-graphic.svg
  src/img/logo/logo-type-bold.svg
  src/img/logo/logo-type-regular.svg
  src/img/menu/announce-1.svg
  src/img/menu/announce-2.svg
  src/img/menu/category.svg
  src/img/menu/help.svg
  src/img/menu/info.svg
  src/img/menu/logout.svg
  src/img/menu/mypage.svg
  src/img/menu/often-todo.svg
  src/img/navi/add.svg
  src/img/navi/all.svg
  src/img/navi/back.svg
  src/img/navi/bell-o.svg
  src/img/navi/bell-x.svg
  src/img/navi/close.svg
  src/img/navi/menu.svg
  src/img/navi/more.svg
  src/img/toggle/off.svg
  src/img/toggle/on.svg
  src/layout/footer/components/Modal.jsx
  src/layout/header/components/DropdownMenu.jsx
  src/layout/header/components/useDetectClose.jsx
  src/layout/header/screen/Header.jsx
  src/pages/MonthlyLog.jsx
  src/shared/Router.jsx
Labels: feat

#22 design: 메인페이지 레이아웃 작업
  src/components/calendar/Calendar.jsx
  src/components/common/NavigationMenu.jsx
  src/components/common/SelectCategory.jsx
  src/components/main/components/BulletDiv.jsx
  src/components/main/screen/MainContainer.jsx
  src/img/bullet/check-2.svg
  src/layout/footer/Footer.jsx
  src/pages/DailyLog.jsx
  src/pages/Login.jsx
  src/pages/MonthlyLog.jsx
  src/pages/SignUp.jsx
  src/shared/GlobalStyle.jsx
Labels: design

#23 시작화면, 로그인, 회원가입 페이지 레이아웃 및 기능구현 - Feat/#9
  package.json
  src/components/logIn/components/LogInInput.jsx
  src/components/logIn/screen/LogInContainer.jsx
  src/components/signup/components/SignUpInput.jsx
  src/components/signup/screen/SignUpContainer.jsx
  src/components/startpage/StartPage.jsx
  src/core/encrypt.jsx
  src/img/Menu_Icon.svg
  src/img/logo/logo-graphic.svg
  src/img/logo/logo-type-bold.svg
  src/layout/footer/components/Modal.jsx
  src/pages/Start.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: feat

#27 시작화면 변경 Feat#25
  src/components/signup/components/SignUpInput.jsx
  src/components/startpage/StartPage.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Router.jsx
Labels: feat

#32 데일리로그 추가페이지 기능 구현중
  src/components/common/NavigationMenu.jsx
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/add/components/TimeSettingDiv.jsx
  src/components/dailyLog/add/screen/AddDailyLogContainer.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/main/components/MainEditCard.jsx
  src/components/main/components/MainInputCard.jsx
  src/components/main/screen/MainContainer.jsx
  src/components/signup/components/SignUpInput.jsx
  src/layout/Layout.jsx
  src/layout/footer/Footer.jsx
  src/redux/modules/bulletTodoSlice.js
  src/shared/GlobalStyle.jsx
Labels: feat, design

#33 Mypage,Search,Category 페이지 생성완료 Feat#29
  public/index.html
  src/components/category/components/CategoryBtn.jsx
  src/components/category/components/CategoryModal.jsx
  src/components/category/screen/CategoryContainer.jsx
  src/components/logIn/screen/LogInContainer.jsx
  src/components/modal/Modal.jsx
  src/components/monthlyLog/screen/MonthlyLogContainer.jsx
  src/components/mypage/components/AlwaysTodo.jsx
  src/components/mypage/components/CatergoryList.jsx
  src/components/mypage/screen/MypageContainer.jsx
  src/components/mypage/screen/MypageInfoButton.jsx
  src/components/mypage/screen/MypageInfoScreen.jsx
  src/components/search/screen/SearchContainer.jsx
  src/components/signup/components/SignUpInput.jsx
  src/components/signup/screen/SignUpContainer.jsx
  src/components/startpage/StartPage.jsx
  src/img/logo/logo-graphic.svg
  src/layout/header/components/DropdownMenu.jsx
  src/layout/header/components/useDetectClose.jsx
  src/layout/header/screen/Header.jsx
  src/pages/MonthlyLog.jsx
  src/pages/Mypage.jsx
  src/pages/Search.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Router.jsx
Labels: feat, design

#35 feat: 할일추가 시간 선택 기능, 할일 입력 수정 기능 및 각 컴포넌트 분리
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/add/components/SelectHoursList.jsx
  src/components/dailyLog/add/components/SelectMinutesList.jsx
  src/components/dailyLog/add/components/TimeSettingDiv.jsx
Labels: feat

#36 전체 Layout 설정 Feat#29
  package.json
  src/components/category/components/CategoryModal.jsx
  src/components/common/NavigationMenu.jsx
  src/components/common/calendar/Calendar.jsx
  src/components/common/modal/Modal.jsx
  src/components/dailyLog/add/screen/AddDailyLogContainer.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/main/screen/MainContainer.jsx
  src/components/mypage/screen/MypageInfoButton.jsx
  src/components/search/screen/SearchContainer.jsx
  src/img/Question_Icon.svg
  src/img/logo/logo-type-bold.svg
  src/img/menu/help.svg
  src/layout/Layout.jsx
  src/layout/footer/Footer.jsx
  src/layout/header/screen/Header.jsx
  src/pages/AddDailyLog.jsx
  src/pages/Category.jsx
  src/pages/DailyLog.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Mypage.jsx
  src/pages/Search.jsx
  src/pages/SignUp.jsx
  src/pages/Start.jsx
  yarn.lock
Labels: feat, design

#38 feat: 할일 메모 삭제 기능
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/layout/Layout.jsx
  src/layout/footer/Footer.jsx
  src/layout/header/screen/Header.jsx
  src/pages/Login.jsx
Labels: feat

#42 refactor: 할일 메모 id값 제외한 포스트 요청으로 수정
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
Labels: refactor

#43 feat: mypage 조회 완료 - Feat#40
  src/components/mypage/components/category/components/CategoryModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/mypage/screen/MypageContainer.jsx
Labels: feat

#45 feat: logout 버튼생성
  src/components/mypage/screen/MypageLogout.jsx
  src/core/cookieControler.jsx
  src/pages/Mypage.jsx
Labels: feat

#49 design: Header,Footer 레이아웃 변경
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/img/logo/logo-graphic.svg
  src/layout/footer/Footer.jsx
  src/layout/footer/components/NavigationMenu.jsx
  src/layout/header/components/Modal.jsx
  src/layout/header/screen/Header.jsx
Labels: design

#51 Design: 마이페이지,카테고리,로그아웃버튼 디자인변경
  src/components/mypage/components/category/components/CategoryAddBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/mypage/components/category/screen/CategoryList.jsx
  src/components/mypage/screen/MypageContainer.jsx
  src/components/mypage/screen/MypageInfoButton.jsx
  src/components/mypage/screen/MypageInfoScreen.jsx
  src/components/mypage/screen/MypageLogout.jsx
  src/pages/Mypage.jsx
  src/redux/modules/categorySlice.js
  src/shared/Router.jsx
Labels: design

#53 feat: 데일리로그 할일 추가 db 통신
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/shared/GlobalStyle.jsx
Labels: feat

#58 design: 옵션 메뉴 삭제 버튼 모달 구현
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/components/BulletSwitchList.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
Labels: design

#61 feat: 할일 추가 페이지 카테고리 선택 기능 및 레이아웃 작업
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/add/components/TimeSettingDiv.jsx
  src/img/dailyLog/add.svg
Labels: feat, design

#63 feat: 메인페이지 조회 기능 구현
  src/components/main/screen/MainContainer.jsx
Labels: feat, design

#65 feat: logout modal 생성
  public/index.html
  src/components/common/modal/AlertModal.jsx
  src/components/common/modal/ConfirmModal.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/mypage/screen/MypageLogout.jsx
  src/components/signup/components/SignUpInput.jsx
Labels: feat

#69 design: Diary, Calendar, HelpModal Layout 그리기
  src/components/common/calendar/Calendar.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/img/diary/check-2.svg
  src/img/diary/edit.svg
  src/img/emotion/angry.svg
  src/layout/Layout.jsx
  src/layout/footer/components/NavigationMenu.jsx
  src/layout/header/components/HelpModal.jsx
  src/layout/header/screen/Header.jsx
  src/pages/Diary.jsx
  src/shared/Router.jsx
Labels: design

#72 feat: 할일 추가 새로고침 반영, 옵션 개별 클릭 기능
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/components/Option.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/layout/Layout.jsx
  src/shared/GlobalStyle.jsx
Labels: feat

#74 feat: 자주쓰는할일(루틴) 추가기능 구현
  src/components/common/modal/ConfirmModal.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddBtn.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal2.jsx
  src/components/mypage/components/category/components/CategoryAddBtn.jsx
  src/components/mypage/components/category/components/CategoryAddModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/signup/components/SignUpInput.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/favoriteSlice.js
  src/shared/GlobalStyle.jsx
Labels: feat

#76 design: Startpage, Mypage CSS 수정
  src/components/logIn/components/LogInInput.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddBtn.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal2.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/screen/AlwaysTodoList.jsx
  src/components/mypage/components/category/components/CategoryAddBtn.jsx
  src/components/mypage/components/category/components/CategoryAddModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/mypage/components/category/screen/CategoryList.jsx
  src/components/mypage/screen/MypageInfoButton.jsx
  src/components/startpage/StartPage.jsx
  src/redux/modules/favoriteSlice.js
Labels: design

#77 #75 feat: 불렛크기 수정, 할일 추가 기능 수정, 할일 삭제 기능 구현
  src/components/dailyLog/add/components/AddMemoDiv.jsx
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/components/BulletSwitchList.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/components/Option.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/img/dailyLog/close.svg
Labels: feat

#78 feat:루틴 조회 기능구현
  src/components/logIn/components/LogInInput.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/screen/AlwaysTodoList.jsx
  src/components/mypage/components/category/screen/CategoryList.jsx
  src/redux/modules/favoriteSlice.js
Labels: feat

#80 #79 feat: 메인페이지 할일 조회기능
  src/components/common/calendar/Calendar.jsx
  src/components/main/screen/MainContainer.jsx
Labels: feat

#82 feat: 루틴 삭제 기능구현, 루틴+카테고리 오류 수정
  src/components/mypage/components/alwaystodo/components/AlwaysAddBtn.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateBtn.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/mypage/components/alwaystodo/screen/AlwaysTodoList.jsx
  src/components/mypage/components/category/components/CategoryAddBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/mypage/components/category/screen/CategoryList.jsx
  src/components/mypage/screen/MypageInfoScreen.jsx
  src/redux/modules/categorySlice.js
  src/redux/modules/favoriteSlice.js
Labels: feat, design

#84 feat: 루틴 수정 기능 구현 완료
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/redux/modules/favoriteSlice.js
Labels: feat

#87 feat: 할일 추가 리덕스 통신, 카테고리 색상 적용, 할일 수정기능(메모 제외) #75
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/add/components/CategorySelectDiv.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/components/Option.jsx
  src/components/dailyLog/edit/components/EditTodoForm.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/edit/screen/EditDailyLogContainer.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/redux/modules/dailysSlice.js
Labels: feat

#88 design: 전체 Layout 디자인 작업
  src/components/common/calendar/Calendar.jsx
  src/components/logIn/components/LogInInput.jsx
  src/components/logIn/screen/LogInContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/components/startpage/StartPage.jsx
  src/img/login/logo-graphic.svg
  src/img/start/logo-graphic.svg
  src/img/start/logo-type-bold.svg
  src/layout/Layout.jsx
  src/layout/StartLayout.jsx
  src/layout/footer/components/NavigationMenu.jsx
  src/layout/footer/screen/Footer.jsx
  src/layout/header/screen/Header.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Router.jsx
Labels: design

#90 #75 feat: 데일리로그 할일 카테고리별 보기 기능 작업
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/components/AllTodoShow.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/components/CategoryButton.jsx
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/components/SelectCategoryTodoShow.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
Labels: feat, design

#92 feat: 데일리로그 자주 쓰는 할 일 추가 기능
  src/components/dailyLog/add/components/AddTodoInput.jsx
  src/components/dailyLog/components/CategorySelector.jsx
  src/components/dailyLog/components/FavoriteTodoCard.jsx
  src/components/dailyLog/components/ModalFavoriteTodo.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/redux/modules/dailysSlice.js
  src/shared/GlobalStyle.jsx
Labels: feat, design

#93 feat: 검색 페이지 기능 구현
  src/components/search/components/SearchTodo.jsx
  src/components/search/screen/SearchContainer.jsx
  src/img/search/close.svg
  src/redux/modules/searchSlice.js
  src/shared/GlobalStyle.jsx
Labels: feat

#94 #75 feat: 자주 쓰는 할 일 리듀서 추가
  src/redux/modules/dailysSlice.js
Labels: feat

#99 feat: 데일리로그 선택 날짜별 할 일 조회 기능
  src/components/common/calendar/DailyLogCalendar.jsx
  src/components/dailyLog/add/components/BulletTodoForm.jsx
  src/components/dailyLog/components/BulletTodoCard.jsx
  src/components/dailyLog/components/CalendarModal.jsx
  src/components/dailyLog/components/FavoriteTodoCard.jsx
  src/components/dailyLog/edit/components/CategorySelectDiv.jsx
  src/components/dailyLog/edit/components/EditTodoInput.jsx
  src/components/dailyLog/screen/DailyLogContainer.jsx
  src/redux/modules/dailysSlice.js
Labels: feat, design

#100 feat: keyword 없을시 안보여주기 ( 빈칸일때 자동검색 X )
  src/components/search/components/SearchTodo.jsx
  src/components/search/screen/SearchContainer.jsx
Labels: feat

#101 feat: 이메일 인증 기능 구현 , category/routine CSS 수정
  src/components/mypage/components/alwaystodo/components/AlwaysAddModal.jsx
  src/components/mypage/components/alwaystodo/components/AlwaysTodo.jsx
  src/components/mypage/components/alwaystodo/components/AwaysUpdateModal.jsx
  src/components/mypage/components/category/components/CategoryAddModal.jsx
  src/components/mypage/components/category/components/CategoryUpdateBtn.jsx
  src/components/mypage/components/category/components/CategoryUpdateModal.jsx
  src/components/mypage/screen/MypageInfoButton.jsx
  src/components/signup/components/SignUpInput.jsx
  src/img/myPage/round-star-outline.svg
Labels: feat, design

#103 feat: 메인페이지 캘린더 조회 기능
  src/components/common/calendar/Calendar.jsx
  src/components/main/screen/MainContainer.jsx
  src/redux/modules/mainSlice.js
Labels: feat, design

#104 feat: 메인페이지 날짜별 할 일 목록 조회 기능, 월별 할 일 카운트 구현
  src/components/common/calendar/MainCalendar.jsx
  src/components/diary/screen/DiaryContainer.jsx
  src/components/main/screen/MainContainer.jsx
  src/redux/modules/mainSlice.js
Labels: feat, design
